### ISSUE TITLE
executing bin from `/tmp` causes trouble on some unix distributions

### ISSUE THREAD

**Issue by bcoe** [isaacs/spawn-wrap#3]
https://github.com/rvagg/through2/pull/48, CC: @rvagg

**Comment by rvagg** [comment]
perhaps switch to using cwd if `EPERM`

**Comment by isaacs** [comment]
Another idea is just to write this to somewhere in `$HOME`.  It *should* always clean up after itself, but at least it could be in something like `~/.node-spawn-wrap/...` so you can tell what it is.

**Comment by stevemao** [comment]
would `$HOME` have the same problem as `/tmp/`? could you mount it as noexec?

**Comment by rvagg** [comment]
@stevemao yes, I've never seen that done though

**Comment by stevemao** [comment]
@rvagg 
Does it mean it potentially is still a problem?

**Comment by rvagg** [comment]
@stevemao yes, but an unlikely one, you could fall-back to cwd or __dirname but ... there are no guarantees anywhere!

**Comment by isaacs** [comment]
The one place we KNOW you can exec something (`path.dirname(process.execPath)`) we probably don't have permission to write to.  So it's a bit of a sticky situation no matter what.  `$HOME` is the best bet.  Breaks travis for some reason I can't owrk out though.  Oh well, bedtime for me.
