### ISSUE TITLE
exec() has issues on *nix systems

### ISSUE THREAD

**Issue by bcoe** [isaacs/spawn-wrap#9]
The old test-suite, which used `exec()` runs on OSX, but fails on Travis and Ubuntu 14.04:

https://gist.github.com/bcoe/574f20564e423375d0a6

We should dig into the issues with `exec()` and add some targeted tests.

**Comment by isaacs** [comment]
Addressed in docs https://github.com/isaacs/spawn-wrap#contracts-and-caveats
